/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocElementsRouteImport } from './routes/doc-elements'
import { Route as IndexRouteImport } from './routes/index'

const DocElementsRoute = DocElementsRouteImport.update({
  id: '/doc-elements',
  path: '/doc-elements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doc-elements': typeof DocElementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doc-elements': typeof DocElementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doc-elements': typeof DocElementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doc-elements'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doc-elements'
  id: '__root__' | '/' | '/doc-elements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocElementsRoute: typeof DocElementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/doc-elements': {
      id: '/doc-elements'
      path: '/doc-elements'
      fullPath: '/doc-elements'
      preLoaderRoute: typeof DocElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocElementsRoute: DocElementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
